name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.x'
          channel: 'stable'
      - run: flutter pub get
      - name: test
        run: dart tool/grind.dart